[database]
  name = "belajar"
  username = "dev"
  password = "dev_password"
  host = "127.0.0.1"
  port = 3306
  option = "?parseTime=true&charset=utf8mb4&loc=Local"

[server]
  host = "localhost"
  addr = ":8080"
