app:
  name: Todo App
  description: "Excepteur fugiat culpa proident occaecat consectetur eiusmod sit irure mollit pariatur."
  languageCode: id
  version: v0.0.1
  copyright: Copyright (c) 2026 Putra Jaya. All Rights Reserved.

server:
  host: localhost
  port: ":8080"

dataFiles:
  session: "data/sessions.json"
  user: "data/users.json"
  todo: "data/todo.json"
